version: '3.7'
services:
  frontend:
    container_name: frontend
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
